name: deploy-book

# Only run this when the master branch changes
on:
  # Se activa automáticamente al subir cambios a master
  push:
    branches:
    - master
  # Se activa manualmente desde la pestaña "Actions"
  workflow_dispatch:    

permissions:
  contents: write
  
# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

# Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install jupyter-book==0.7.0b1
        
    - name: Build the book
      run: |
        jupyter-book build .
        
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        force_orphan: true
